### ISSUE TITLE
ScriptHoovDotNet/RagePluginHook Issue Resolved yet?

### ISSUE THREAD

**Issue by CriminalJustice** [crosire/scripthookvdotnet#1175]
So if this is in fact an issue with Rage Plugin Hook and it looks like thats the case, then why don't someone from this website communicate with someone over on Rage Plugin Hook to try and get this issue worked out? I just don't get why it hasn't been fixed yet. Allot of us play LSPDFR with a scripts folder therefore requiring Rage plugin Hook to run our game. So, what's the issue with getting some communication between ScriptHooVDotNet and Rage Plugin Hook?

**Comment by crosire** [comment]
It was solved in 29ba91ea83c9ae5b11356485faa4c063144f0903.

**Comment by LegacyEffect** [comment]
No it was not resolved.  This has been an ongoing issue for a VERY long time.

**Comment by kagikn** [comment]
@LegacyEffect Have you tried the latest dev build, which does not ruin C++ exceptions and the exe keeps running when RPH plugins throw unhandled exceptions? Download [the zip file of the latest build](https://ci.appveyor.com/project/crosire/scripthookvdotnet/builds/46765738/artifacts) and see if the issue still happens.

All official releases (v3.6.0 or earlier) suffer the issue, but I'm thinking we will release the next one within a month.
