### ISSUE TITLE
Add correct ExplosionTypes

### ISSUE THREAD

**Issue by Yothri** [crosire/scripthookvdotnet#222]
Can someone please update the World.cpp and correct the Explosion Enumeration to those:

```cs
enum ExplosionTypes
{
EXPLOSION_GRENADE,
EXPLOSION_GRENADELAUNCHER,
EXPLOSION_STICKYBOMB,
EXPLOSION_MOLOTOV,
EXPLOSION_ROCKET,
EXPLOSION_TANKSHELL,
EXPLOSION_HI_OCTANE,
EXPLOSION_CAR,
EXPLOSION_PLANE,
EXPLOSION_PETROL_PUMP,
EXPLOSION_BIKE,
EXPLOSION_DIR_STEAM,
EXPLOSION_DIR_FLAME,
EXPLOSION_DIR_WATER_HYDRANT,
EXPLOSION_DIR_GAS_CANISTER,
EXPLOSION_BOAT,
EXPLOSION_SHIP_DESTROY,
EXPLOSION_TRUCK,
EXPLOSION_BULLET,
EXPLOSION_SMOKEGRENADELAUNCHER,
EXPLOSION_SMOKEGRENADE,
EXPLOSION_BZGAS,
EXPLOSION_FLARE,
EXPLOSION_GAS_CANISTER,
EXPLOSION_EXTINGUISHER,
EXPLOSION_PROGRAMMABLEAR,
EXPLOSION_TRAIN,
EXPLOSION_BARREL,
EXPLOSION_PROPANE,
EXPLOSION_BLIMP,
EXPLOSION_DIR_FLAME_EXPLODE,
EXPLOSION_TANKER,
EXPLOSION_PLANE_ROCKET,
EXPLOSION_VEHICLE_BULLET,
EXPLOSION_GAS_TANK,
EXPLOSION_BIRD_CRAP
};
```

Found them in the NativeDB.

**Comment by BenjaminFaal** [comment]
By looking at the code this issue should be solved.

**Comment by Yothri** [comment]
Allright.

**Comment by JohnnyCrazy** [comment]
@BenjaminFaal How comes? The names are still wrong in the files

**Comment by BenjaminFaal** [comment]
@JohnnyCrazy Hmm weird, i thought they added it. Im sorry.

**Comment by JohnnyCrazy** [comment]
No problem :)

**Comment by JohnnyCrazy** [comment]
Updated in #292

**Comment by zorg93** [comment]
whoops I removed them when fixing merge issues, fixed up in that pr though
