### ISSUE TITLE
Scripts that don't directly inherit from GTA.Script won't load on separate_api builds

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#873]
[Just checking full name of classes' base type](https://github.com/crosire/scripthookvdotnet/blob/3d2f77157ca6a250c221fcc15633ad557452fcb4/source/core/ScriptDomain.cs#L285) ignores scripts that are subclasses of `GTA.Script` but doesn't directly inherit from it. Some script mods use abstract classes that inherit from `GTA.Script` for advanced controls. Any solutions?

**Comment by crosire** [comment]
This should work now with https://github.com/crosire/scripthookvdotnet/commit/e1fabca9fcafc68ce6629d44e2d68169b8e33410.

**Comment by kagikn** [comment]
All scripts I have work now with https://github.com/crosire/scripthookvdotnet/commit/e1fabca9fcafc68ce6629d44e2d68169b8e33410. If I should find scripts that still don't work with that commit, I'll reopen this issue.
